import { ListingResult } from "./types";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

export function generateMarkdown(result: ListingResult): string {
  const date = new Date((result as any).createdAt || Date.now()).toLocaleDateString();

  const kwMap = result.analysis?.competitorKeywordMap
    .map((kw) => `- **${kw.keyword}**: Found in ${kw.frequency}/${kw.totalCompetitors} competitors (${kw.classification})`)
    .join("\n") || "";

  const gaps = result.analysis?.keywordGaps.map((gap) => `- ${gap}`).join("\n") || "";
  const bullets = result.bullets.map((b, i) => `${i + 1}. ${b}`).join("\n");

  return `# Amazon Listing Optimization Report — ${result.productName}
Generated by ListingMaker on ${date}

## SEO & AI Metrics
- **SEO Score:** ${result.analysis?.seoScore}/100
- **Rufus AI Score:** ${result.analysis?.rufusScore}/100
- **Primary Keyword:** ${result.keywordsUsed.primary}

## Optimized Listing

### Title (${result.title.length} characters)
${result.title}

### Bullet Points
${bullets}

### Product Description
${result.description}

### Backend Search Terms
${result.backendKeywords}

---
## Competitor Keyword Map
${kwMap}

### Keyword Gaps Exploited
${gaps}

---
*Created with ListingMaker*
`;
}

export function downloadMarkdown(result: ListingResult) {
  const content = generateMarkdown(result);
  const blob = new Blob([content], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const slug = (result.productName ?? "product").toLowerCase().replace(/\s+/g, "-");
  link.download = `listing-${slug}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function downloadPDF(elementId: string, filename: string) {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    const canvas = await html2canvas(element, {
      scale: 1.5, // Slightly lower scale to prevent memory issues
      useCORS: true,
      backgroundColor: "#050508",
      logging: false,
      windowWidth: element.scrollWidth,
      windowHeight: element.scrollHeight,
    });

    const imgData = canvas.toDataURL("image/jpeg", 0.95);
    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "px",
      format: [canvas.width, canvas.height],
    });

    pdf.addImage(imgData, "JPEG", 0, 0, canvas.width, canvas.height);
    pdf.save(`${filename}.pdf`);
  } catch (error) {
    console.error("PDF generation failed:", error);
    alert("PDF generation failed. Using default print fallback...");
    window.print();
  }
}
